# DevOps Philosophy & Tooling

DevOps is a self-help philosophy for IT and software development teams that work together. It seeks to address a core problem: **The Fear of Taking Code into Production**

The whole point of this workshop is to get you some experience with what it takes to get Shiny Applications running in 

- Deployments/releases are high-risk events
- It takes a long time to deliver new features to customers
- There is no visibility into how code is deployed into production, therefore it is impossible to know what to optimize or fix in the system and/or people who seek to improve portions of workflow are likely not addressing true bottlenecks.
- Dev and Ops have seemingly conflicting goals and objectives

The Fix (ref: The DevOps Handbook) "The principles underpinning DevOps": 

1. Accelerate the delivery of work from Development to Operations to customers
2. Commit to evolving ever safer systems of work through feedback
3. Promote a high-trust culture and embrace continual learning and experimentation (risk-taking) in daily work

---

**Flow**

- Make work visible
- Limit Work in Progress (WIP)
- Reduce Batch Sizes
- Reduce the number of handoffs
- Continually identify and elevate constraints 
- Eliminate hardships and waste in the value stream

Typical DevOps Transformation (pg. 22)
- Environment creation
- Code Deployment
- Test setup and run
- Overly tight architechture

**Feedback**

- Working safely within complex systems
  - Complex work is managed so that problems in design and operations are revealed
  - Problems are swarmed and solved
  - New local knowledge is exploited globally throughout the organization
  - Leaders create leaders
- See problems as they occur
- Swarm and solve problems to build new knowledge
- Keep pushing quality closer to the source
- Enable optimizing for downstream work centers

**Continual Learning & Experimentation**

- Enable organizational learning and a safety culture
- Institutionalize the improvement of daily work
- Transform local discoveries into global improvements
- Inject resilience patterns into daily work

Generative organizations (pg. 39) // What type of organization do you have? Comparison Activity
- Information is actively sought
- Messengers are trained
- Responsibilities are shared
- Bridging between teams is rewarded
- Failure causes inquiry
- New ideas are welcomed

> Even more important than daily work is the improvement of daily work  --Mike Orzen, Lean IT

#### DevOps Vocab 101

Deployment Lead Time

Hardships and Waste:
- Partially done work
- Extra processes
- Extra features
- Task switching
- Waiting
- Motion
- Defects
- Nonstandard or manual work
- Heroics

#### Integrating Data Science and DevOps

##### How does data science fit in with the DevOps philosophy?

It's not _your job_ to understand operations and systems administration. And it's not IT's job to understand R programming and shiny app development. But it takes shared goals and a little empathy from both sides to get less painful results.

We can leverage (steal) the DevOps philosophy and apply it to manage code deployment handoffs between data science and IT.

Foundations:

What do your dev, test and production environments look like?
- Do developers have access to production-like environments on their own workstations?
- Can these evnvironments be assembled on-demand?
  - Version Control
  - Infrastructure as Code



##### Design and Management of Analytic Infrastructure (alternative architectures)

##### Programatic Deployment into RStudio Connect

##### Deployment Release Patterns

- Environment based release patterns
- Application based release patterns

#### Feature Toggles (Dark Launch)

##### User meta-data

Shiny applications can access the username and groups of the current user through the session parameter of the shinyServer function.

Groups meta-data is populated when using password, or OAuth authentication. It is not populated with LDAP, PAM, or proxy authentication.

```
shinyServer(function(input, output, session) {
  output$username <- reactive({
    session$user
  })
  
  output$groups <- reactive({
    session$groups
  })
})
```

Your application could use this information to display customized messages or to enable functionality for a specific subset of users.


#### Extended Topics & Resources

**Shiny Application Usage (Instrumentation)**

RStudio Connect exposes usage information about shiny applications that will tell you which ones have been used, by whom and for how long. It is available via an API that may be used by administrators or publishers. Publishers may retrieve information about their own applications only.

More information about using the API is included in the historical information chapter of the RStudio Connect Admin Guide.